name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build and test for iOS
      run: xcodebuild clean build -project Tickers.xcodeproj -scheme "Tickers" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPhone 15" ONLY_ACTIVE_ARCH=YES test
